#!/bin/bash

echo "🚀 API TESTING WITH POSTMAN & SWAGGER"
echo "====================================="
echo ""

echo "📋 AVAILABLE TOOLS:"
echo "1. ✅ Postman: Installed and ready"
echo "2. ✅ Swagger UI: Running on http://localhost:8080"
echo "3. ✅ API Collection: Marketing-Analytics-API.postman_collection.json"
echo "4. ✅ OpenAPI Spec: api-spec.json"
echo ""

echo "🔗 ACCESS POINTS:"
echo "- Swagger UI: http://localhost:8080"
echo "- Development Server: http://localhost:3000"
echo "- API Testing Page: http://localhost:3000/api-testing"
echo ""

echo "📊 CURRENT SYSTEM STATUS:"
echo "========================="
echo "✅ Google Sheets: CONNECTED (steve@tulenagency.com)"
echo "✅ GoHighLevel: CONNECTED (Magnolia Terrace)"
echo "✅ Facebook Ads: CONNECTED (All Accounts)"
echo "❌ Google Ads: NOT CONNECTED (OAuth fixed, needs reconnection)"
echo ""

echo "🧪 TESTING INSTRUCTIONS:"
echo "========================"
echo "1. Open Postman and import: Marketing-Analytics-API.postman_collection.json"
echo "2. Open Swagger UI: http://localhost:8080"
echo "3. Test API endpoints using either tool"
echo "4. Check API Testing Dashboard: http://localhost:3000/api-testing"
echo ""

echo "🎯 EXPECTED RESULTS:"
echo "===================="
echo "- Venues API: Should return Magnolia Terrace venue"
echo "- Google Sheets API: Should work (connected)"
echo "- GoHighLevel API: Should work (connected)"
echo "- Facebook Ads API: Should work (connected)"
echo "- Google Ads API: Will fail (not connected)"
echo ""

echo "📝 NEXT STEPS:"
echo "=============="
echo "1. Test APIs using Postman or Swagger UI"
echo "2. Fix Google Ads OAuth connection"
echo "3. Verify all API calls work correctly"
echo "4. Document any issues found"
